# Generated by Django 5.1 on 2025-08-18 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreport',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to staff'),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='is_rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
