# Generated by Django 5.1 on 2025-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_itemreport_admin_notes_itemreport_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='collection_confirmed_by_reporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='collection_notes',
            field=models.TextField(blank=True, help_text='Notes about the collection (location, condition, etc.)'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COLLECTED', 'Collected')], default='PENDING', max_length=10),
        ),
    ]
